JOURNAL_SOURCE=yandex-public-cache
YANDEX_DISK_PUBLIC_URL=https://disk.yandex.ru/i/sGTYC8nUWYAsRw
YANDEX_DISK_PUBLIC_PATH=
JOURNAL_CACHE_INTERVAL_MINUTES=30
JOURNAL_CACHE_MAX_FILES=2
JOURNAL_CACHE_DIR=./.journal-cache
